// flow-typed signature: 9dbbf79d02dad31e3f58028091b92da3
// flow-typed version: <<STUB>>/async-middleware_v^1.2.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-middleware/dist/index' {
  declare module.exports: any;
}

declare module 'async-middleware/dist/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-middleware/dist/index.js' {
  declare module.exports: $Exports<'async-middleware/dist/index'>;
}
declare module 'async-middleware/dist/index.spec.js' {
  declare module.exports: $Exports<'async-middleware/dist/index.spec'>;
}
