// flow-typed signature: 1d16771c55db5b93af063ca373b9b49a
// flow-typed version: <<STUB>>/eslint-plugin-import-order_v2.1.4/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-import-order/rules/import-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-import-order/index' {
  declare module.exports: $Exports<'eslint-plugin-import-order'>;
}
declare module 'eslint-plugin-import-order/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order'>;
}
declare module 'eslint-plugin-import-order/rules/import-order.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order/rules/import-order'>;
}
declare module 'eslint-plugin-import-order/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order/utils'>;
}
